name: manga_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.5

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get_it: ^8.0.1
  talker: ^4.4.1
  talker_flutter: ^4.4.5
  talker_dio_logger: ^4.4.5
  talker_bloc_logger: ^4.4.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  window_manager: ^0.4.3
  supabase_flutter: ^2.8.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  url_launcher: ^6.3.1
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.2
  auto_route: ^9.2.2
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.1
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  image_path: "assets/logo/icon.png"
  android: "launcher_icon"
  min_sdk_android: 21

  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/